name:                synths
version:             0.1.0.0
github:              "netom/synths"
license:             BSD3
author:              "Fábián Tamás László"
maintainer:          "giganetom@gmail.com"
copyright:           "2019 Fábián Tamás László"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/buf#readme>

dependencies:
- base >= 4.7 && < 5
- vector
- primitive
- bytestring
- memory

library:
  source-dirs: src

executables:
  synths:
    main:                Main.hs
    source-dirs:         app
    #ghc-options:
    #- -threaded
    #- -rtsopts
    #- -with-rtsopts=-N
    #- -fllvm
    #- -msse2
    dependencies:
    - synths

tests:
  synths-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - synths
